AWSTemplateFormatVersion: 2010-09-09
Description: aws-sns-sds-dojo
Parameters:
    TriggerRuleName:
        Description: Trigger Rule Name
        Default: trigger-event-rules
        Type: String

Resources:
    MySNSTopic:
        Type: AWS::SNS::Topic
        Properties:
          DisplayName: MyAlarmSNSTopic
          Subscription:
            - Endpoint: yxwang@thoughtworks.com
              Protocol: email
            - Endpoint: !GetAtt MySQSQueue.Arn
              Protocol: sqs
          TopicName: "MySNSTopicName"

    MySNSPolicy:    
        Type: AWS::SNS::TopicPolicy
        Properties:
            PolicyDocument:
                Id: MyTopicPolicy
                Version: '2012-10-17'
                Statement:
                    - Sid: My-statement-id
                      Effect: Allow
                      Principal:
                        AWS: "*"
                      Action: SNS:Publish
                      Resource: "*"
            Topics:
                - !Ref MySNSTopic

    MySQSQueue:
        Type: AWS::SQS::Queue
        Properties:
            QueueName: "MySQSQueueName"
            MessageRetentionPeriod: 604800 # 7days
            VisibilityTimeout: 300 # 5min

    SNSScheduleTriggerRule:
        Type: AWS::Events::Rule
        Properties:
          ScheduleExpression: cron(0/1 * * * ? *) #todo 5min
          Targets:
            - Id: !Ref TriggerRuleName
              Arn: !Ref MySNSTopic




